### ISSUE TITLE
 ` 符号呈现非等宽宽度

### ISSUE THREAD

**Issue by laomao800** [iyannik0215/YaHei-Consolas-Hybrid-1.12#2]
`  符号呈现非等宽宽度，但换了系统自带的 Consolas 字体并不会。

封装的 Consolas 版本太低的缘故？

**Comment by iyannik0215** [comment]
` 和 ' 在这个字体里面长的一模一样, 但是这个字体并不是我搞出来的.. 我也不太清楚... 我只是用 github 记录一下安装的命令罢了, 2333 .

**Comment by fengjianyun** [comment]
@laomao800 我建了个pull request #8, 修改了反引号（`）的角度，你可以试试，我在Windows 10下测试没问题。
